"""empty message

Revision ID: a108f2d35480
Revises: 
Create Date: 2024-11-15 17:36:30.000273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a108f2d35480'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_robots')
    with op.batch_alter_table('robots', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('ip',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'127.0.1'"))
        batch_op.alter_column('port',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'9090'"))
        batch_op.alter_column('map_topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'map'"))
        batch_op.alter_column('laser_topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'scan'"))
        batch_op.alter_column('global_path_topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'/plan'"))
        batch_op.alter_column('local_path_topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'/local_plan'"))
        batch_op.alter_column('reloc_topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'/initialpose'"))
        batch_op.alter_column('nav_goal_topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'/goal_pose'"))
        batch_op.alter_column('odometry_topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'/wheel/odometry'"))
        batch_op.alter_column('speed_ctrl_topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'/cmd_vel'"))
        batch_op.alter_column('battery_topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'/battery_status'"))
        batch_op.alter_column('max_vx',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.1)'))
        batch_op.alter_column('max_vy',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.1)'))
        batch_op.alter_column('max_vw',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.3)'))
        batch_op.alter_column('map_frame_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'map'"))
        batch_op.alter_column('base_link_frame_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'base_link'"))
        batch_op.alter_column('image_port',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'8080'"))
        batch_op.alter_column('image_topic',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'/camera/image_raw'"))
        batch_op.alter_column('image_width',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(640.0)'))
        batch_op.alter_column('image_height',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(480.0)'))

    with op.batch_alter_table('voice_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_package', sa.String(length=255), nullable=False, server_default=""))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_record', schema=None) as batch_op:
        batch_op.drop_column('voice_package')

    with op.batch_alter_table('robots', schema=None) as batch_op:
        batch_op.alter_column('image_height',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(480.0)'))
        batch_op.alter_column('image_width',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(640.0)'))
        batch_op.alter_column('image_topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'/camera/image_raw'"))
        batch_op.alter_column('image_port',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'8080'"))
        batch_op.alter_column('base_link_frame_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'base_link'"))
        batch_op.alter_column('map_frame_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'map'"))
        batch_op.alter_column('max_vw',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.3)'))
        batch_op.alter_column('max_vy',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.1)'))
        batch_op.alter_column('max_vx',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.1)'))
        batch_op.alter_column('battery_topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'/battery_status'"))
        batch_op.alter_column('speed_ctrl_topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'/cmd_vel'"))
        batch_op.alter_column('odometry_topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'/wheel/odometry'"))
        batch_op.alter_column('nav_goal_topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'/goal_pose'"))
        batch_op.alter_column('reloc_topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'/initialpose'"))
        batch_op.alter_column('local_path_topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'/local_plan'"))
        batch_op.alter_column('global_path_topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'/plan'"))
        batch_op.alter_column('laser_topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'scan'"))
        batch_op.alter_column('map_topic',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'map'"))
        batch_op.alter_column('port',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'9090'"))
        batch_op.alter_column('ip',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'127.0.1'"))
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_robots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('init', sa.INTEGER(), server_default=sa.text('2'), nullable=True),
    sa.Column('ip', sa.VARCHAR(), server_default=sa.text("'127.0.1'"), nullable=True),
    sa.Column('port', sa.VARCHAR(), server_default=sa.text("'9090'"), nullable=True),
    sa.Column('map_topic', sa.VARCHAR(), server_default=sa.text("'map'"), nullable=True),
    sa.Column('laser_topic', sa.VARCHAR(), server_default=sa.text("'scan'"), nullable=True),
    sa.Column('global_path_topic', sa.VARCHAR(), server_default=sa.text("'/plan'"), nullable=True),
    sa.Column('local_path_topic', sa.VARCHAR(), server_default=sa.text("'/local_plan'"), nullable=True),
    sa.Column('reloc_topic', sa.VARCHAR(), server_default=sa.text("'/initialpose'"), nullable=True),
    sa.Column('nav_goal_topic', sa.VARCHAR(), server_default=sa.text("'/goal_pose'"), nullable=True),
    sa.Column('odometry_topic', sa.VARCHAR(), server_default=sa.text("'/wheel/odometry'"), nullable=True),
    sa.Column('speed_ctrl_topic', sa.VARCHAR(), server_default=sa.text("'/cmd_vel'"), nullable=True),
    sa.Column('battery_topic', sa.VARCHAR(), server_default=sa.text("'/battery_status'"), nullable=True),
    sa.Column('max_vx', sa.FLOAT(), server_default=sa.text('(0.1)'), nullable=True),
    sa.Column('max_vy', sa.FLOAT(), server_default=sa.text('(0.1)'), nullable=True),
    sa.Column('max_vw', sa.FLOAT(), server_default=sa.text('(0.3)'), nullable=True),
    sa.Column('map_frame_name', sa.VARCHAR(), server_default=sa.text("'map'"), nullable=True),
    sa.Column('base_link_frame_name', sa.VARCHAR(), server_default=sa.text("'base_link'"), nullable=True),
    sa.Column('image_port', sa.VARCHAR(), server_default=sa.text("'8080'"), nullable=True),
    sa.Column('image_topic', sa.VARCHAR(), server_default=sa.text("'/camera/image_raw'"), nullable=True),
    sa.Column('image_width', sa.FLOAT(), server_default=sa.text('(640.0)'), nullable=True),
    sa.Column('image_height', sa.FLOAT(), server_default=sa.text('(480.0)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
